language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  chmod +x gradlew #권한부여

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r haeseung-springbootStudy-webservice * # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - mkdir -p deploy # deploy 디렉토리 생성
  - mv haeseung-springbootStudy-webservice.zip deploy/haeseung-springbootStudy-webservice.zip # deploy로 zip파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: haeseung-springbootstudy-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: haeseung-springbootstudy-build # S3 버킷
    key: haeseung-springbootStudy-webservice  # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: haeseung-springbootStudy-webservice-group #웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - dlgotmd93@gmail.com